# Site settings
title: Alexa and Rudy
email: tieleknot@gmail.com
url: https://example.github.io
description: "01.03.2018"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#eff2f3'
  links: '#219ab3'

# Footer settings
footer: AR Wedding

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
