# Site settings
title: Rodolfo Gutiérrez 
email: rodolf.gutierrez@gmail.com
description: "This is my new website. Look for increased functionality and features in the near future."
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
