# Site settings
title: Rodolfo Gutierrez
email: rodolf.gutierrez@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://rodolfo12.github.io"
url: "http://rodolfogutierrez.com"

# Build settings
markdown: kramdown
permalink: pretty
