# Site settings
title: Alexa &amp; Rudy1
email: tieleknot@gmail.com
url: https://example.github.io
description: "01.03.2018 <br /> Juchipila, Zac, Mx."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000'
  links: '#fff'

# Footer settings
footer: arwedding

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
# Build settings
markdown: kramdown
permalink: pretty
