# Site settings
title: Rodolfo Gutiérrez
email: rodolf.gutierrez@gmail.com
description: "This is my new website. I am incrementally building off current template features and enhancing my web programming abilities in the /process."
baseurl: ""
url: "http://rodolfogutierrez.com"

# Build settings
markdown: kramdown
permalink: pretty
