# Site settings
title: Rodolfo Gutiérrez's Homepage
email: rodolf.gutierrez@gmail.com
description: "First, solve the problem. Then, write the code. -John Johnson" 
baseurl: ""
url: ""
sdl: "https://www.libsdl.org"


# Build settings
markdown: kramdown
permalink: pretty
